# Generated by Django 5.1.5 on 2025-11-16 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_partner_user_workplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('percent', models.PositiveIntegerField(help_text='Bonus percent added to top-up amount, 1-100')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='topuptransaction',
            name='promo_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='topuptransaction',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topups', to='core.promocode'),
        ),
        migrations.CreateModel(
            name='PromocodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='core.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'promocode')},
            },
        ),
    ]
